# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

use_frameworks! :linkage => :static
# WARNING #
# Facebook Audience Network require dynamic linkage by default
# If want to use static linkage it is required to add an empty swift file to the project
# Refer to: https://developers.facebook.com/docs/audience-network/setting-up/platform-setup/ios/add-sdk/#notes

target 'PIXAdManagerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for PIXAdManagerDemo
  pod 'Google-Mobile-Ads-SDK', '~> 9.11.0'
  
  pod 'AppLovinSDK', '~> 11.5.0'
  
  pod 'FBAudienceNetwork', '~> 6.12.0'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end